{% set name = "sanic-plugins-framework" %}
{% set version = "0.9.4.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Sanic-Plugins-Framework-{{ version }}.tar.gz
  sha256: eea5b874c15255467c21acfb2e8b16b0e6bff5d11dffed698c63b2e759f3ec50

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sanic >=18.12.0
    - setuptools >=40.0

test:
  imports:
    - spf
    - spf.plugins
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashleysommer/sanicpluginsframework
  summary: Doing all of the boilerplate to create a Sanic Plugin, so you don't have to.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - patricksnape
